language: python
python:
- '2.7'
before_script:
- wget https://github.com/Berach/BERACHS_COMPLETE_PIDGIN/archive/master.zip -O /tmp/berach_pidgin.zip
- unzip -q /tmp/berach_pidgin.zip
script:
- python emoticonset_builder ./BERACHS_COMPLETE_PIDGIN-master ./Berach_Complete_Adium.AdiumEmoticonSet
after_script:
- tar -czf Berach_Complete_Adium.tar.gz Berach_Complete_Adium.AdiumEmoticonSet
deploy:
  provider: releases
  api_key:
    secure: NOjgaBqq5lkbjRcIz68ZJHOTnR2N/aTbtDCD7qr1Q+1UDN+XTn4JZNnmKS6+WLvbjaIYKuIaSgk5YWDa3WiajKmmswknTZHq6YbB26EA1GThkTT1AV7g/fRipsVimrxnhUSUyI+fM97SWaCbJvqrKnIIAIWOE0ZCiriOS7S65yZSS3xYnYJXXTwYzeuTWjxp5US7PAxwOpylmCfvCFO7V/ybfDL0dvKFg0l1aM3xJzVgMuuJ2Bi5Y5JTEpz7R5GXqrmMUKtiwwDGE3HoadTbIEJpLPFICtC/AvUnowHk4Eplb0v9qh9eKD1wfLgWLOsGsnfFGhSeuqum/qBSHv665A8sE1j1smlk5q7wIdCwj392MUuVVNy42XjMMWSVikEnl6e095cblHTILCniLTeJ315Zz4o8Sj0iUl2t1i99MXkbFbpNjgktP6EqrV+Rziuog2CpUXSYODShN9UKvOk6000Z7kj4cCiZ+pb3iK9u21ctguDSpvsBxv9PszyIjQYNKybJ3odq2ImQoGTszFiwRsTRBSAaGonfzpKET5be6uGaxgOUKP7E4//M0aZTs7DRUBiWxv0EXKDptfedQhOi6Oaamf7p7+elSDjxdXAtYzwMAPOjTCnR5VKpbSAtfcleM9HUHJylvDpTOvVPzQ1BcTqDHmHhWrznic7ktfCptBY=
  file: Berach_Complete_Adium.tar.gz
  on:
    repo: Krylik/Pidgin2AdiumEmoticons
  skip_cleanup: true
  on:
    tags: true
